# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop'
gem 'json'
gem 'imgkit'

gem "byebug", "~> 11.1", :groups => [:development, :test]
